rails/w10d1_hw_capybara_tests/music_app_capybara/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create] #sign up, see profile
  resource :session, only: [:new, :create, :destroy] #login & logout

  resources :bands

end

rails/w10d1_hw_capybara_tests/music_app_capybara/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/w10d1_hw_capybara_tests/music_app_capybara/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true
  
end

rails/w10d1_hw_capybara_tests/music_app_capybara/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: {message: "can't be blank"}
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  

end

  # subject(:user) {User.new(email: "", password: "") }
  
  # describe "validations" do
  #   it { should validate_presence_of(:email) }
  #   it { should validate_presence_of(:password_digest) }
  #   it { should validate_length_of(:password).is_at_least(6) }
  # end
  
  # # describe "associations" do
  # #   it { should have_many(:??)}
  # # end
  
  # describe "class methods" do
  #   describe "::find_by_credentials" do
  #     it { should validate_presence_of(:email)}
  #   end
  # end

rails/w10d1_hw_capybara_tests/music_app_capybara/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :login, :logged_in?
  #app controller can access user model methods
  #helper_method makes these available to the views

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    @current_user = nil
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

end

rails/w10d1_hw_capybara_tests/music_app_capybara/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      
    else
      # flash.now[:errors] = 
    end
    
  end

  def new
    @band = Band.new
    render :new
  end

  def show
  
  end

  def edit
  
  end

  def update
  
  end

  def destroy
  
  end

  private
  
  def band_params
    params.require(:band).permit(:name)
  end

end

rails/w10d1_hw_capybara_tests/music_app_capybara/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new #login page
    render :new
  end

  def create #login button
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    # remember these should be symbols!
    # they give us the params in the form of email, pw
    # we find in db

    if user #exist in db?
      login(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["invalid username or password"]
      render :new
    end

  end

  def destroy #logout button
    logout
    redirect_to new_session_url
  end

end

rails/w10d1_hw_capybara_tests/music_app_capybara/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new #sign up page
    @user = User.new
    render :new
  end

  # to access old values as pre-selected/defaults in an edit form (if we are using a partial)

  def create #sign up button
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show #shows user profile
    @user = User.find(params[:id]) #fetch user id from url(params)
    #remember not to use find_by here
    # can't use user_params here because they didn't fill out a form
    render :show #uses @user to make the view customized to that logged in user (or not logged in)
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
    #require a top level key of user, allow us to access email and pw within it.
  end

end

rails/w10d1_hw_capybara_tests/music_app_capybara/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/w10d1_hw_capybara_tests/music_app_capybara/app/helpers/bands_helper.rb
module BandsHelper
end

rails/w10d1_hw_capybara_tests/music_app_capybara/app/helpers/sessions_helper.rb
module SessionsHelper
end

rails/w10d1_hw_capybara_tests/music_app_capybara/app/helpers/users_helper.rb
module UsersHelper
end

rails/w10d1_hw_capybara_tests/music_app_capybara/app/views/bands/index.html.erb
<h1>Band List:</h1>
<%= @bands %>

rails/w10d1_hw_capybara_tests/music_app_capybara/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="main-content" >

      <h1 class="main-logo" > Music App</h1>
      <% if logged_in? %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        
        <input class="button" type="submit" value="logout">
      </form>
      <% else %>
      <a href="<%= new_user_url %>" class="button" >Sign Up</a>
      <% end %>
      <%= yield %>
      <%= flash[:errors] if flash[:errors] %>
    </div>
  </body>
</html>

rails/w10d1_hw_capybara_tests/music_app_capybara/app/views/users/new.html.erb
<h1>Sign up as a new user!</h1>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="email">Email</label>
  <input type="text" name="user[email]" id="email"><br>
  
  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password"><br>

  <input type="submit" value="Sign Up!">

</form>

rails/w10d1_hw_capybara_tests/music_app_capybara/app/views/users/show.html.erb
<h1>Welcome <%= @user.email %>! </h1>